### PR TITLE
fix: jina math is now in docarray

### PR DESCRIPTION
**Pull request by davidbp**

### CODE REVIEW

**Review by JoanFM — COMMENTED** [review]
Has the dependency been updated?

**Comment by davidbp** [comment]
We still use `JinaLogger` so not sure about removing jina as a dependency

**Comment by davidbp** [comment]
Even if we don't `Executor` is  the main thing we use from Jina.

**Review by numb3r3 — CHANGES_REQUESTED** [review]
Also please add `docarray` into `requirements.txt`

**Pull request merged**
